dist: bionic

language: python
python:
  - "3.6"

before_install:
  - sudo /sbin/ldconfig -v

install:
  - pip3 install -r requirements.txt

script:
  - python3 -m unittest discover -s test -p '*_test.py'